# Generated by Django 5.2.6 on 2025-09-29 09:58

import django.db.models.deletion
import management.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=20, unique=True, validators=[management.validators.validate_cif], verbose_name='CIF')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_commercials', models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Comerciales Asignados')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='management.company', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('REUNION', 'Reunión Presencial/Virtual'), ('OTRO', 'Otro')], default='LLAMADA', max_length=10, verbose_name='Tipo de Interacción')),
                ('notes', models.TextField(verbose_name='Notas / Resumen')),
                ('interaction_date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='management.client', verbose_name='Cliente')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Comercial')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
